name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Génère tous les jours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SamuelSgn25
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate snake animation"
          add: "dist/github-contribution-grid-snake.svg"
