name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"


      - name: Add banner image
        run: |
          mkdir -p assets
  
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update README with Samuel-Banner" || echo "No changes to commit"
          git push
